// Copyright 2023 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer to stream scientific data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: root.proto

package root_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	tree_go_proto "multiscope/protos/tree_go_proto"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Multiscope metadata (e.g. UI layout).
type RootInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	KeySettings string                 `protobuf:"bytes,1,opt,name=key_settings,json=keySettings,proto3" json:"key_settings,omitempty"`
	Layout      *Layout                `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	// Display the capture so that keyboard and mouse events can be captured
	// and send back to the client.
	EnableCapture bool `protobuf:"varint,3,opt,name=enable_capture,json=enableCapture,proto3" json:"enable_capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootInfo) Reset() {
	*x = RootInfo{}
	mi := &file_root_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootInfo) ProtoMessage() {}

func (x *RootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootInfo.ProtoReflect.Descriptor instead.
func (*RootInfo) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{0}
}

func (x *RootInfo) GetKeySettings() string {
	if x != nil {
		return x.KeySettings
	}
	return ""
}

func (x *RootInfo) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *RootInfo) GetEnableCapture() bool {
	if x != nil {
		return x.EnableCapture
	}
	return false
}

type LayoutList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default height of a row.
	DefaultRowHeight int32 `protobuf:"varint,1,opt,name=defaultRowHeight,proto3" json:"defaultRowHeight,omitempty"`
	// Paths to be displayed.
	Displayed     []*tree_go_proto.NodePath `protobuf:"bytes,2,rep,name=displayed,proto3" json:"displayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayoutList) Reset() {
	*x = LayoutList{}
	mi := &file_root_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayoutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutList) ProtoMessage() {}

func (x *LayoutList) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutList.ProtoReflect.Descriptor instead.
func (*LayoutList) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{1}
}

func (x *LayoutList) GetDefaultRowHeight() int32 {
	if x != nil {
		return x.DefaultRowHeight
	}
	return 0
}

func (x *LayoutList) GetDisplayed() []*tree_go_proto.NodePath {
	if x != nil {
		return x.Displayed
	}
	return nil
}

// Message to store layout data such as node path to display.
type Layout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Layout:
	//
	//	*Layout_List
	Layout        isLayout_Layout `protobuf_oneof:"layout"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layout) Reset() {
	*x = Layout{}
	mi := &file_root_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{2}
}

func (x *Layout) GetLayout() isLayout_Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *Layout) GetList() *LayoutList {
	if x != nil {
		if x, ok := x.Layout.(*Layout_List); ok {
			return x.List
		}
	}
	return nil
}

type isLayout_Layout interface {
	isLayout_Layout()
}

type Layout_List struct {
	List *LayoutList `protobuf:"bytes,1,opt,name=list,proto3,oneof"`
}

func (*Layout_List) isLayout_Layout() {}

// Sets the key for the UI settings.
type SetKeySettingsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TreeId *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// Key string identifies identifies the binary being run to fetch the
	// corresponding settings.
	KeySettings   string `protobuf:"bytes,2,opt,name=key_settings,json=keySettings,proto3" json:"key_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeySettingsRequest) Reset() {
	*x = SetKeySettingsRequest{}
	mi := &file_root_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeySettingsRequest) ProtoMessage() {}

func (x *SetKeySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeySettingsRequest.ProtoReflect.Descriptor instead.
func (*SetKeySettingsRequest) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{3}
}

func (x *SetKeySettingsRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *SetKeySettingsRequest) GetKeySettings() string {
	if x != nil {
		return x.KeySettings
	}
	return ""
}

type SetKeySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKeySettingsResponse) Reset() {
	*x = SetKeySettingsResponse{}
	mi := &file_root_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKeySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeySettingsResponse) ProtoMessage() {}

func (x *SetKeySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeySettingsResponse.ProtoReflect.Descriptor instead.
func (*SetKeySettingsResponse) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{4}
}

// Sets the layout to display.
type SetLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Layout        *Layout                `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLayoutRequest) Reset() {
	*x = SetLayoutRequest{}
	mi := &file_root_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayoutRequest) ProtoMessage() {}

func (x *SetLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayoutRequest.ProtoReflect.Descriptor instead.
func (*SetLayoutRequest) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{5}
}

func (x *SetLayoutRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *SetLayoutRequest) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

type SetLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLayoutResponse) Reset() {
	*x = SetLayoutResponse{}
	mi := &file_root_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayoutResponse) ProtoMessage() {}

func (x *SetLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayoutResponse.ProtoReflect.Descriptor instead.
func (*SetLayoutResponse) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{6}
}

// Sets if the capture button should be displayed or not.
type SetCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Capture       bool                   `protobuf:"varint,2,opt,name=capture,proto3" json:"capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCaptureRequest) Reset() {
	*x = SetCaptureRequest{}
	mi := &file_root_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCaptureRequest) ProtoMessage() {}

func (x *SetCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCaptureRequest.ProtoReflect.Descriptor instead.
func (*SetCaptureRequest) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{7}
}

func (x *SetCaptureRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *SetCaptureRequest) GetCapture() bool {
	if x != nil {
		return x.Capture
	}
	return false
}

type SetCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCaptureResponse) Reset() {
	*x = SetCaptureResponse{}
	mi := &file_root_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCaptureResponse) ProtoMessage() {}

func (x *SetCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCaptureResponse.ProtoReflect.Descriptor instead.
func (*SetCaptureResponse) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{8}
}

// Get root info.
type GetRootInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootInfoRequest) Reset() {
	*x = GetRootInfoRequest{}
	mi := &file_root_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootInfoRequest) ProtoMessage() {}

func (x *GetRootInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRootInfoRequest) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{9}
}

func (x *GetRootInfoRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

type GetRootInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *RootInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootInfoResponse) Reset() {
	*x = GetRootInfoResponse{}
	mi := &file_root_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootInfoResponse) ProtoMessage() {}

func (x *GetRootInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRootInfoResponse) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{10}
}

func (x *GetRootInfoResponse) GetInfo() *RootInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_root_proto protoreflect.FileDescriptor

const file_root_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"root.proto\x12\x0fmultiscope.root\x1a\n" +
	"tree.proto\"\x85\x01\n" +
	"\bRootInfo\x12!\n" +
	"\fkey_settings\x18\x01 \x01(\tR\vkeySettings\x12/\n" +
	"\x06layout\x18\x02 \x01(\v2\x17.multiscope.root.LayoutR\x06layout\x12%\n" +
	"\x0eenable_capture\x18\x03 \x01(\bR\renableCapture\"l\n" +
	"\n" +
	"LayoutList\x12*\n" +
	"\x10defaultRowHeight\x18\x01 \x01(\x05R\x10defaultRowHeight\x122\n" +
	"\tdisplayed\x18\x02 \x03(\v2\x14.multiscope.NodePathR\tdisplayed\"E\n" +
	"\x06Layout\x121\n" +
	"\x04list\x18\x01 \x01(\v2\x1b.multiscope.root.LayoutListH\x00R\x04listB\b\n" +
	"\x06layout\"g\n" +
	"\x15SetKeySettingsRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12!\n" +
	"\fkey_settings\x18\x02 \x01(\tR\vkeySettings\"\x18\n" +
	"\x16SetKeySettingsResponse\"p\n" +
	"\x10SetLayoutRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12/\n" +
	"\x06layout\x18\x02 \x01(\v2\x17.multiscope.root.LayoutR\x06layout\"\x13\n" +
	"\x11SetLayoutResponse\"Z\n" +
	"\x11SetCaptureRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12\x18\n" +
	"\acapture\x18\x02 \x01(\bR\acapture\"\x14\n" +
	"\x12SetCaptureResponse\"A\n" +
	"\x12GetRootInfoRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\"D\n" +
	"\x13GetRootInfoResponse\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.multiscope.root.RootInfoR\x04info2\xf6\x02\n" +
	"\x04Root\x12Z\n" +
	"\vGetRootInfo\x12#.multiscope.root.GetRootInfoRequest\x1a$.multiscope.root.GetRootInfoResponse\"\x00\x12c\n" +
	"\x0eSetKeySettings\x12&.multiscope.root.SetKeySettingsRequest\x1a'.multiscope.root.SetKeySettingsResponse\"\x00\x12T\n" +
	"\tSetLayout\x12!.multiscope.root.SetLayoutRequest\x1a\".multiscope.root.SetLayoutResponse\"\x00\x12W\n" +
	"\n" +
	"SetCapture\x12\".multiscope.root.SetCaptureRequest\x1a#.multiscope.root.SetCaptureResponse\"\x00B!Z\x1fmultiscope/protos/root_go_protob\x06proto3"

var (
	file_root_proto_rawDescOnce sync.Once
	file_root_proto_rawDescData []byte
)

func file_root_proto_rawDescGZIP() []byte {
	file_root_proto_rawDescOnce.Do(func() {
		file_root_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_root_proto_rawDesc), len(file_root_proto_rawDesc)))
	})
	return file_root_proto_rawDescData
}

var file_root_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_root_proto_goTypes = []any{
	(*RootInfo)(nil),               // 0: multiscope.root.RootInfo
	(*LayoutList)(nil),             // 1: multiscope.root.LayoutList
	(*Layout)(nil),                 // 2: multiscope.root.Layout
	(*SetKeySettingsRequest)(nil),  // 3: multiscope.root.SetKeySettingsRequest
	(*SetKeySettingsResponse)(nil), // 4: multiscope.root.SetKeySettingsResponse
	(*SetLayoutRequest)(nil),       // 5: multiscope.root.SetLayoutRequest
	(*SetLayoutResponse)(nil),      // 6: multiscope.root.SetLayoutResponse
	(*SetCaptureRequest)(nil),      // 7: multiscope.root.SetCaptureRequest
	(*SetCaptureResponse)(nil),     // 8: multiscope.root.SetCaptureResponse
	(*GetRootInfoRequest)(nil),     // 9: multiscope.root.GetRootInfoRequest
	(*GetRootInfoResponse)(nil),    // 10: multiscope.root.GetRootInfoResponse
	(*tree_go_proto.NodePath)(nil), // 11: multiscope.NodePath
	(*tree_go_proto.TreeID)(nil),   // 12: multiscope.TreeID
}
var file_root_proto_depIdxs = []int32{
	2,  // 0: multiscope.root.RootInfo.layout:type_name -> multiscope.root.Layout
	11, // 1: multiscope.root.LayoutList.displayed:type_name -> multiscope.NodePath
	1,  // 2: multiscope.root.Layout.list:type_name -> multiscope.root.LayoutList
	12, // 3: multiscope.root.SetKeySettingsRequest.tree_id:type_name -> multiscope.TreeID
	12, // 4: multiscope.root.SetLayoutRequest.tree_id:type_name -> multiscope.TreeID
	2,  // 5: multiscope.root.SetLayoutRequest.layout:type_name -> multiscope.root.Layout
	12, // 6: multiscope.root.SetCaptureRequest.tree_id:type_name -> multiscope.TreeID
	12, // 7: multiscope.root.GetRootInfoRequest.tree_id:type_name -> multiscope.TreeID
	0,  // 8: multiscope.root.GetRootInfoResponse.info:type_name -> multiscope.root.RootInfo
	9,  // 9: multiscope.root.Root.GetRootInfo:input_type -> multiscope.root.GetRootInfoRequest
	3,  // 10: multiscope.root.Root.SetKeySettings:input_type -> multiscope.root.SetKeySettingsRequest
	5,  // 11: multiscope.root.Root.SetLayout:input_type -> multiscope.root.SetLayoutRequest
	7,  // 12: multiscope.root.Root.SetCapture:input_type -> multiscope.root.SetCaptureRequest
	10, // 13: multiscope.root.Root.GetRootInfo:output_type -> multiscope.root.GetRootInfoResponse
	4,  // 14: multiscope.root.Root.SetKeySettings:output_type -> multiscope.root.SetKeySettingsResponse
	6,  // 15: multiscope.root.Root.SetLayout:output_type -> multiscope.root.SetLayoutResponse
	8,  // 16: multiscope.root.Root.SetCapture:output_type -> multiscope.root.SetCaptureResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_root_proto_init() }
func file_root_proto_init() {
	if File_root_proto != nil {
		return
	}
	file_root_proto_msgTypes[2].OneofWrappers = []any{
		(*Layout_List)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_root_proto_rawDesc), len(file_root_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_root_proto_goTypes,
		DependencyIndexes: file_root_proto_depIdxs,
		MessageInfos:      file_root_proto_msgTypes,
	}.Build()
	File_root_proto = out.File
	file_root_proto_goTypes = nil
	file_root_proto_depIdxs = nil
}
