// Protocol buffer to stream scientific data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: root.proto

package root_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	tree_go_proto "multiscope/protos/tree_go_proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Multiscope metadata (e.g. UI layout).
type RootInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout *Layout `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *RootInfo) Reset() {
	*x = RootInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootInfo) ProtoMessage() {}

func (x *RootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootInfo.ProtoReflect.Descriptor instead.
func (*RootInfo) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{0}
}

func (x *RootInfo) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

// Message to store layout data such as node path to display.
type Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Paths to be displayed.
	Displayed []*tree_go_proto.NodePath `protobuf:"bytes,2,rep,name=displayed,proto3" json:"displayed,omitempty"`
}

func (x *Layout) Reset() {
	*x = Layout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{1}
}

func (x *Layout) GetDisplayed() []*tree_go_proto.NodePath {
	if x != nil {
		return x.Displayed
	}
	return nil
}

// Sets the layout to display.
type SetLayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout *Layout `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *SetLayoutRequest) Reset() {
	*x = SetLayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayoutRequest) ProtoMessage() {}

func (x *SetLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayoutRequest.ProtoReflect.Descriptor instead.
func (*SetLayoutRequest) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{2}
}

func (x *SetLayoutRequest) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

type SetLayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLayoutResponse) Reset() {
	*x = SetLayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLayoutResponse) ProtoMessage() {}

func (x *SetLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_root_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLayoutResponse.ProtoReflect.Descriptor instead.
func (*SetLayoutResponse) Descriptor() ([]byte, []int) {
	return file_root_proto_rawDescGZIP(), []int{3}
}

var File_root_proto protoreflect.FileDescriptor

var file_root_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x2e, 0x72, 0x6f, 0x6f, 0x74, 0x1a, 0x0a, 0x74,
	0x72, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x08, 0x52, 0x6f, 0x6f,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x2e, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x22, 0x3c, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x12, 0x32, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x09, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x64, 0x22, 0x43, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x2e, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5c,
	0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x54, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x12, 0x21, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x63, 0x6f, 0x70, 0x65,
	0x2e, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x2e, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_root_proto_rawDescOnce sync.Once
	file_root_proto_rawDescData = file_root_proto_rawDesc
)

func file_root_proto_rawDescGZIP() []byte {
	file_root_proto_rawDescOnce.Do(func() {
		file_root_proto_rawDescData = protoimpl.X.CompressGZIP(file_root_proto_rawDescData)
	})
	return file_root_proto_rawDescData
}

var file_root_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_root_proto_goTypes = []interface{}{
	(*RootInfo)(nil),               // 0: multiscope.root.RootInfo
	(*Layout)(nil),                 // 1: multiscope.root.Layout
	(*SetLayoutRequest)(nil),       // 2: multiscope.root.SetLayoutRequest
	(*SetLayoutResponse)(nil),      // 3: multiscope.root.SetLayoutResponse
	(*tree_go_proto.NodePath)(nil), // 4: multiscope.NodePath
}
var file_root_proto_depIdxs = []int32{
	1, // 0: multiscope.root.RootInfo.layout:type_name -> multiscope.root.Layout
	4, // 1: multiscope.root.Layout.displayed:type_name -> multiscope.NodePath
	1, // 2: multiscope.root.SetLayoutRequest.layout:type_name -> multiscope.root.Layout
	2, // 3: multiscope.root.Root.SetLayout:input_type -> multiscope.root.SetLayoutRequest
	3, // 4: multiscope.root.Root.SetLayout:output_type -> multiscope.root.SetLayoutResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_root_proto_init() }
func file_root_proto_init() {
	if File_root_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_root_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_root_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_root_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_root_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_root_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_root_proto_goTypes,
		DependencyIndexes: file_root_proto_depIdxs,
		MessageInfos:      file_root_proto_msgTypes,
	}.Build()
	File_root_proto = out.File
	file_root_proto_rawDesc = nil
	file_root_proto_goTypes = nil
	file_root_proto_depIdxs = nil
}
