// Copyright 2023 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer to stream scientific data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: ui.proto

package ui_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	tree_go_proto "multiscope/protos/tree_go_proto"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Worker acknowledgement.
type WorkerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerAck) Reset() {
	*x = WorkerAck{}
	mi := &file_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerAck) ProtoMessage() {}

func (x *WorkerAck) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerAck.ProtoReflect.Descriptor instead.
func (*WorkerAck) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

// Message to connect to the httpgrpc server.
type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	TreeId        *tree_go_proto.TreeID  `protobuf:"bytes,3,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	RawUrl        string                 `protobuf:"bytes,4,opt,name=raw_url,json=rawUrl,proto3" json:"raw_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Connect) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Connect) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Connect) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *Connect) GetRawUrl() string {
	if x != nil {
		return x.RawUrl
	}
	return ""
}

// Message to pull data from the server.
type Pull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actives       []uint32               `protobuf:"varint,1,rep,packed,name=actives,proto3" json:"actives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pull) Reset() {
	*x = Pull{}
	mi := &file_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pull) ProtoMessage() {}

func (x *Pull) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pull.ProtoReflect.Descriptor instead.
func (*Pull) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{2}
}

func (x *Pull) GetActives() []uint32 {
	if x != nil {
		return x.Actives
	}
	return nil
}

// Panel registers a panel in the puller webworker.
type Panel struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            uint32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Paths         []*tree_go_proto.NodePath `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	Transferables []uint32                  `protobuf:"varint,3,rep,packed,name=transferables,proto3" json:"transferables,omitempty"`
	Renderer      string                    `protobuf:"bytes,4,opt,name=renderer,proto3" json:"renderer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Panel) Reset() {
	*x = Panel{}
	mi := &file_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Panel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panel) ProtoMessage() {}

func (x *Panel) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panel.ProtoReflect.Descriptor instead.
func (*Panel) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{3}
}

func (x *Panel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Panel) GetPaths() []*tree_go_proto.NodePath {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Panel) GetTransferables() []uint32 {
	if x != nil {
		return x.Transferables
	}
	return nil
}

func (x *Panel) GetRenderer() string {
	if x != nil {
		return x.Renderer
	}
	return ""
}

// StyleChange is sent to the workers to change the theme.
type StyleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	FontFamily    string                 `protobuf:"bytes,2,opt,name=fontFamily,proto3" json:"fontFamily,omitempty"`
	FontSize      float64                `protobuf:"fixed64,3,opt,name=fontSize,proto3" json:"fontSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StyleChange) Reset() {
	*x = StyleChange{}
	mi := &file_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StyleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleChange) ProtoMessage() {}

func (x *StyleChange) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleChange.ProtoReflect.Descriptor instead.
func (*StyleChange) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{4}
}

func (x *StyleChange) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *StyleChange) GetFontFamily() string {
	if x != nil {
		return x.FontFamily
	}
	return ""
}

func (x *StyleChange) GetFontSize() float64 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

type ElementSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,10,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,11,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementSize) Reset() {
	*x = ElementSize{}
	mi := &file_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementSize) ProtoMessage() {}

func (x *ElementSize) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementSize.ProtoReflect.Descriptor instead.
func (*ElementSize) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{5}
}

func (x *ElementSize) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ElementSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// ParentResize is sent when the parent of a renderer is changing its size.
type ParentResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanelID       uint32                 `protobuf:"varint,1,opt,name=panelID,proto3" json:"panelID,omitempty"`
	ChildSize     *ElementSize           `protobuf:"bytes,10,opt,name=childSize,proto3" json:"childSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentResize) Reset() {
	*x = ParentResize{}
	mi := &file_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentResize) ProtoMessage() {}

func (x *ParentResize) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentResize.ProtoReflect.Descriptor instead.
func (*ParentResize) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{6}
}

func (x *ParentResize) GetPanelID() uint32 {
	if x != nil {
		return x.PanelID
	}
	return 0
}

func (x *ParentResize) GetChildSize() *ElementSize {
	if x != nil {
		return x.ChildSize
	}
	return nil
}

// Event dispatched from the main thread to the renderers.
type UIEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*UIEvent_Style
	//	*UIEvent_Resize
	Event         isUIEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIEvent) Reset() {
	*x = UIEvent{}
	mi := &file_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIEvent) ProtoMessage() {}

func (x *UIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIEvent.ProtoReflect.Descriptor instead.
func (*UIEvent) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{7}
}

func (x *UIEvent) GetEvent() isUIEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UIEvent) GetStyle() *StyleChange {
	if x != nil {
		if x, ok := x.Event.(*UIEvent_Style); ok {
			return x.Style
		}
	}
	return nil
}

func (x *UIEvent) GetResize() *ParentResize {
	if x != nil {
		if x, ok := x.Event.(*UIEvent_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isUIEvent_Event interface {
	isUIEvent_Event()
}

type UIEvent_Style struct {
	Style *StyleChange `protobuf:"bytes,10,opt,name=style,proto3,oneof"`
}

type UIEvent_Resize struct {
	Resize *ParentResize `protobuf:"bytes,11,opt,name=resize,proto3,oneof"`
}

func (*UIEvent_Style) isUIEvent_Event() {}

func (*UIEvent_Resize) isUIEvent_Event() {}

type RegisterPanel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Panel         *Panel                 `protobuf:"bytes,1,opt,name=panel,proto3" json:"panel,omitempty"`
	PreferredSize *ElementSize           `protobuf:"bytes,2,opt,name=preferredSize,proto3" json:"preferredSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPanel) Reset() {
	*x = RegisterPanel{}
	mi := &file_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPanel) ProtoMessage() {}

func (x *RegisterPanel) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPanel.ProtoReflect.Descriptor instead.
func (*RegisterPanel) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterPanel) GetPanel() *Panel {
	if x != nil {
		return x.Panel
	}
	return nil
}

func (x *RegisterPanel) GetPreferredSize() *ElementSize {
	if x != nil {
		return x.PreferredSize
	}
	return nil
}

// ToPuller is the message sent to the puller webworker.
type ToPuller struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*ToPuller_Pull
	//	*ToPuller_RegisterPanel
	//	*ToPuller_UnregisterPanel
	//	*ToPuller_Event
	Query         isToPuller_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToPuller) Reset() {
	*x = ToPuller{}
	mi := &file_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToPuller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToPuller) ProtoMessage() {}

func (x *ToPuller) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToPuller.ProtoReflect.Descriptor instead.
func (*ToPuller) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{9}
}

func (x *ToPuller) GetQuery() isToPuller_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ToPuller) GetPull() *Pull {
	if x != nil {
		if x, ok := x.Query.(*ToPuller_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *ToPuller) GetRegisterPanel() *RegisterPanel {
	if x != nil {
		if x, ok := x.Query.(*ToPuller_RegisterPanel); ok {
			return x.RegisterPanel
		}
	}
	return nil
}

func (x *ToPuller) GetUnregisterPanel() *Panel {
	if x != nil {
		if x, ok := x.Query.(*ToPuller_UnregisterPanel); ok {
			return x.UnregisterPanel
		}
	}
	return nil
}

func (x *ToPuller) GetEvent() *UIEvent {
	if x != nil {
		if x, ok := x.Query.(*ToPuller_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isToPuller_Query interface {
	isToPuller_Query()
}

type ToPuller_Pull struct {
	Pull *Pull `protobuf:"bytes,1,opt,name=pull,proto3,oneof"`
}

type ToPuller_RegisterPanel struct {
	RegisterPanel *RegisterPanel `protobuf:"bytes,2,opt,name=registerPanel,proto3,oneof"`
}

type ToPuller_UnregisterPanel struct {
	UnregisterPanel *Panel `protobuf:"bytes,3,opt,name=unregisterPanel,proto3,oneof"`
}

type ToPuller_Event struct {
	Event *UIEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

func (*ToPuller_Pull) isToPuller_Query() {}

func (*ToPuller_RegisterPanel) isToPuller_Query() {}

func (*ToPuller_UnregisterPanel) isToPuller_Query() {}

func (*ToPuller_Event) isToPuller_Query() {}

// Data for a panel.
type PanelData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Nodes         []*tree_go_proto.NodeData `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelData) Reset() {
	*x = PanelData{}
	mi := &file_ui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelData) ProtoMessage() {}

func (x *PanelData) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelData.ProtoReflect.Descriptor instead.
func (*PanelData) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{10}
}

func (x *PanelData) GetNodes() []*tree_go_proto.NodeData {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// Message storing the data to be displayed by the main thread.
type DisplayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          map[uint32]*PanelData  `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisplayData) Reset() {
	*x = DisplayData{}
	mi := &file_ui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayData) ProtoMessage() {}

func (x *DisplayData) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayData.ProtoReflect.Descriptor instead.
func (*DisplayData) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{11}
}

func (x *DisplayData) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *DisplayData) GetData() map[uint32]*PanelData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ui_proto protoreflect.FileDescriptor

const file_ui_proto_rawDesc = "" +
	"\n" +
	"\bui.proto\x12\n" +
	"multiscope\x1a\n" +
	"tree.proto\"\v\n" +
	"\tWorkerAck\"{\n" +
	"\aConnect\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12+\n" +
	"\atree_id\x18\x03 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12\x17\n" +
	"\araw_url\x18\x04 \x01(\tR\x06rawUrl\" \n" +
	"\x04Pull\x12\x18\n" +
	"\aactives\x18\x01 \x03(\rR\aactives\"\x85\x01\n" +
	"\x05Panel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12*\n" +
	"\x05paths\x18\x02 \x03(\v2\x14.multiscope.NodePathR\x05paths\x12$\n" +
	"\rtransferables\x18\x03 \x03(\rR\rtransferables\x12\x1a\n" +
	"\brenderer\x18\x04 \x01(\tR\brenderer\"_\n" +
	"\vStyleChange\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x1e\n" +
	"\n" +
	"fontFamily\x18\x02 \x01(\tR\n" +
	"fontFamily\x12\x1a\n" +
	"\bfontSize\x18\x03 \x01(\x01R\bfontSize\";\n" +
	"\vElementSize\x12\x14\n" +
	"\x05width\x18\n" +
	" \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\v \x01(\x05R\x06height\"_\n" +
	"\fParentResize\x12\x18\n" +
	"\apanelID\x18\x01 \x01(\rR\apanelID\x125\n" +
	"\tchildSize\x18\n" +
	" \x01(\v2\x17.multiscope.ElementSizeR\tchildSize\"w\n" +
	"\aUIEvent\x12/\n" +
	"\x05style\x18\n" +
	" \x01(\v2\x17.multiscope.StyleChangeH\x00R\x05style\x122\n" +
	"\x06resize\x18\v \x01(\v2\x18.multiscope.ParentResizeH\x00R\x06resizeB\a\n" +
	"\x05event\"w\n" +
	"\rRegisterPanel\x12'\n" +
	"\x05panel\x18\x01 \x01(\v2\x11.multiscope.PanelR\x05panel\x12=\n" +
	"\rpreferredSize\x18\x02 \x01(\v2\x17.multiscope.ElementSizeR\rpreferredSize\"\xea\x01\n" +
	"\bToPuller\x12&\n" +
	"\x04pull\x18\x01 \x01(\v2\x10.multiscope.PullH\x00R\x04pull\x12A\n" +
	"\rregisterPanel\x18\x02 \x01(\v2\x19.multiscope.RegisterPanelH\x00R\rregisterPanel\x12=\n" +
	"\x0funregisterPanel\x18\x03 \x01(\v2\x11.multiscope.PanelH\x00R\x0funregisterPanel\x12+\n" +
	"\x05event\x18\x04 \x01(\v2\x13.multiscope.UIEventH\x00R\x05eventB\a\n" +
	"\x05query\"7\n" +
	"\tPanelData\x12*\n" +
	"\x05nodes\x18\x01 \x03(\v2\x14.multiscope.NodeDataR\x05nodes\"\xa6\x01\n" +
	"\vDisplayData\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err\x125\n" +
	"\x04data\x18\x02 \x03(\v2!.multiscope.DisplayData.DataEntryR\x04data\x1aN\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.multiscope.PanelDataR\x05value:\x028\x01B\x1fZ\x1dmultiscope/protos/ui_go_protob\x06proto3"

var (
	file_ui_proto_rawDescOnce sync.Once
	file_ui_proto_rawDescData []byte
)

func file_ui_proto_rawDescGZIP() []byte {
	file_ui_proto_rawDescOnce.Do(func() {
		file_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_proto_rawDesc), len(file_ui_proto_rawDesc)))
	})
	return file_ui_proto_rawDescData
}

var file_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ui_proto_goTypes = []any{
	(*WorkerAck)(nil),              // 0: multiscope.WorkerAck
	(*Connect)(nil),                // 1: multiscope.Connect
	(*Pull)(nil),                   // 2: multiscope.Pull
	(*Panel)(nil),                  // 3: multiscope.Panel
	(*StyleChange)(nil),            // 4: multiscope.StyleChange
	(*ElementSize)(nil),            // 5: multiscope.ElementSize
	(*ParentResize)(nil),           // 6: multiscope.ParentResize
	(*UIEvent)(nil),                // 7: multiscope.UIEvent
	(*RegisterPanel)(nil),          // 8: multiscope.RegisterPanel
	(*ToPuller)(nil),               // 9: multiscope.ToPuller
	(*PanelData)(nil),              // 10: multiscope.PanelData
	(*DisplayData)(nil),            // 11: multiscope.DisplayData
	nil,                            // 12: multiscope.DisplayData.DataEntry
	(*tree_go_proto.TreeID)(nil),   // 13: multiscope.TreeID
	(*tree_go_proto.NodePath)(nil), // 14: multiscope.NodePath
	(*tree_go_proto.NodeData)(nil), // 15: multiscope.NodeData
}
var file_ui_proto_depIdxs = []int32{
	13, // 0: multiscope.Connect.tree_id:type_name -> multiscope.TreeID
	14, // 1: multiscope.Panel.paths:type_name -> multiscope.NodePath
	5,  // 2: multiscope.ParentResize.childSize:type_name -> multiscope.ElementSize
	4,  // 3: multiscope.UIEvent.style:type_name -> multiscope.StyleChange
	6,  // 4: multiscope.UIEvent.resize:type_name -> multiscope.ParentResize
	3,  // 5: multiscope.RegisterPanel.panel:type_name -> multiscope.Panel
	5,  // 6: multiscope.RegisterPanel.preferredSize:type_name -> multiscope.ElementSize
	2,  // 7: multiscope.ToPuller.pull:type_name -> multiscope.Pull
	8,  // 8: multiscope.ToPuller.registerPanel:type_name -> multiscope.RegisterPanel
	3,  // 9: multiscope.ToPuller.unregisterPanel:type_name -> multiscope.Panel
	7,  // 10: multiscope.ToPuller.event:type_name -> multiscope.UIEvent
	15, // 11: multiscope.PanelData.nodes:type_name -> multiscope.NodeData
	12, // 12: multiscope.DisplayData.data:type_name -> multiscope.DisplayData.DataEntry
	10, // 13: multiscope.DisplayData.DataEntry.value:type_name -> multiscope.PanelData
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ui_proto_init() }
func file_ui_proto_init() {
	if File_ui_proto != nil {
		return
	}
	file_ui_proto_msgTypes[7].OneofWrappers = []any{
		(*UIEvent_Style)(nil),
		(*UIEvent_Resize)(nil),
	}
	file_ui_proto_msgTypes[9].OneofWrappers = []any{
		(*ToPuller_Pull)(nil),
		(*ToPuller_RegisterPanel)(nil),
		(*ToPuller_UnregisterPanel)(nil),
		(*ToPuller_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_proto_rawDesc), len(file_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ui_proto_goTypes,
		DependencyIndexes: file_ui_proto_depIdxs,
		MessageInfos:      file_ui_proto_msgTypes,
	}.Build()
	File_ui_proto = out.File
	file_ui_proto_goTypes = nil
	file_ui_proto_depIdxs = nil
}
