// Copyright 2023 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer to stream text data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: scalar.proto

package scalar_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	tree_go_proto "multiscope/protos/tree_go_proto"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Writer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TreeId *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// Path in the Multiscope tree.
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Writer) Reset() {
	*x = Writer{}
	mi := &file_scalar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Writer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Writer) ProtoMessage() {}

func (x *Writer) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Writer.ProtoReflect.Descriptor instead.
func (*Writer) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{0}
}

func (x *Writer) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *Writer) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Request to create a new writer in the tree.
type NewWriterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID   `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWriterRequest) Reset() {
	*x = NewWriterRequest{}
	mi := &file_scalar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWriterRequest) ProtoMessage() {}

func (x *NewWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWriterRequest.ProtoReflect.Descriptor instead.
func (*NewWriterRequest) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{1}
}

func (x *NewWriterRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *NewWriterRequest) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Response after creating a new writer in the tree.
type NewWriterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *Writer                `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWriterResponse) Reset() {
	*x = NewWriterResponse{}
	mi := &file_scalar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWriterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWriterResponse) ProtoMessage() {}

func (x *NewWriterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWriterResponse.ProtoReflect.Descriptor instead.
func (*NewWriterResponse) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{2}
}

func (x *NewWriterResponse) GetWriter() *Writer {
	if x != nil {
		return x.Writer
	}
	return nil
}

// Request to write a scalars data.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *Writer                `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	LabelToValue  map[string]float64     `protobuf:"bytes,2,rep,name=label_to_value,json=labelToValue,proto3" json:"label_to_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_scalar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequest) GetWriter() *Writer {
	if x != nil {
		return x.Writer
	}
	return nil
}

func (x *WriteRequest) GetLabelToValue() map[string]float64 {
	if x != nil {
		return x.LabelToValue
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_scalar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_scalar_proto_rawDescGZIP(), []int{4}
}

var File_scalar_proto protoreflect.FileDescriptor

const file_scalar_proto_rawDesc = "" +
	"\n" +
	"\fscalar.proto\x12\x11multiscope.scalar\x1a\n" +
	"tree.proto\"_\n" +
	"\x06Writer\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"i\n" +
	"\x10NewWriterRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"F\n" +
	"\x11NewWriterResponse\x121\n" +
	"\x06writer\x18\x01 \x01(\v2\x19.multiscope.scalar.WriterR\x06writer\"\xdb\x01\n" +
	"\fWriteRequest\x121\n" +
	"\x06writer\x18\x01 \x01(\v2\x19.multiscope.scalar.WriterR\x06writer\x12W\n" +
	"\x0elabel_to_value\x18\x02 \x03(\v21.multiscope.scalar.WriteRequest.LabelToValueEntryR\flabelToValue\x1a?\n" +
	"\x11LabelToValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x0f\n" +
	"\rWriteResponse2\xb1\x01\n" +
	"\aScalars\x12X\n" +
	"\tNewWriter\x12#.multiscope.scalar.NewWriterRequest\x1a$.multiscope.scalar.NewWriterResponse\"\x00\x12L\n" +
	"\x05Write\x12\x1f.multiscope.scalar.WriteRequest\x1a .multiscope.scalar.WriteResponse\"\x00B#Z!multiscope/protos/scalar_go_protob\x06proto3"

var (
	file_scalar_proto_rawDescOnce sync.Once
	file_scalar_proto_rawDescData []byte
)

func file_scalar_proto_rawDescGZIP() []byte {
	file_scalar_proto_rawDescOnce.Do(func() {
		file_scalar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)))
	})
	return file_scalar_proto_rawDescData
}

var file_scalar_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scalar_proto_goTypes = []any{
	(*Writer)(nil),                 // 0: multiscope.scalar.Writer
	(*NewWriterRequest)(nil),       // 1: multiscope.scalar.NewWriterRequest
	(*NewWriterResponse)(nil),      // 2: multiscope.scalar.NewWriterResponse
	(*WriteRequest)(nil),           // 3: multiscope.scalar.WriteRequest
	(*WriteResponse)(nil),          // 4: multiscope.scalar.WriteResponse
	nil,                            // 5: multiscope.scalar.WriteRequest.LabelToValueEntry
	(*tree_go_proto.TreeID)(nil),   // 6: multiscope.TreeID
	(*tree_go_proto.NodePath)(nil), // 7: multiscope.NodePath
}
var file_scalar_proto_depIdxs = []int32{
	6, // 0: multiscope.scalar.Writer.tree_id:type_name -> multiscope.TreeID
	7, // 1: multiscope.scalar.Writer.path:type_name -> multiscope.NodePath
	6, // 2: multiscope.scalar.NewWriterRequest.tree_id:type_name -> multiscope.TreeID
	7, // 3: multiscope.scalar.NewWriterRequest.path:type_name -> multiscope.NodePath
	0, // 4: multiscope.scalar.NewWriterResponse.writer:type_name -> multiscope.scalar.Writer
	0, // 5: multiscope.scalar.WriteRequest.writer:type_name -> multiscope.scalar.Writer
	5, // 6: multiscope.scalar.WriteRequest.label_to_value:type_name -> multiscope.scalar.WriteRequest.LabelToValueEntry
	1, // 7: multiscope.scalar.Scalars.NewWriter:input_type -> multiscope.scalar.NewWriterRequest
	3, // 8: multiscope.scalar.Scalars.Write:input_type -> multiscope.scalar.WriteRequest
	2, // 9: multiscope.scalar.Scalars.NewWriter:output_type -> multiscope.scalar.NewWriterResponse
	4, // 10: multiscope.scalar.Scalars.Write:output_type -> multiscope.scalar.WriteResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_scalar_proto_init() }
func file_scalar_proto_init() {
	if File_scalar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalar_proto_rawDesc), len(file_scalar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalar_proto_goTypes,
		DependencyIndexes: file_scalar_proto_depIdxs,
		MessageInfos:      file_scalar_proto_msgTypes,
	}.Build()
	File_scalar_proto = out.File
	file_scalar_proto_goTypes = nil
	file_scalar_proto_depIdxs = nil
}
