# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiscope/protos/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emultiscope/protos/events.proto\x12\x11multiscope.events\"k\n\x06Widget\x12\x11\n\twidget_id\x18\x01 \x01(\x03\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x1e.multiscope.events.Widget.Type\" \n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05\x43LICK\x10\x01\"\xa8\x01\n\x08Keyboard\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .multiscope.events.Keyboard.Type\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x08\x12\x0c\n\x04\x63trl\x18\x04 \x01(\x08\x12\r\n\x05shift\x18\x05 \x01(\x08\x12\x0c\n\x04meta\x18\x06 \x01(\x08\"\'\n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\"\xe0\x01\n\x05Mouse\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x12\n\nposition_x\x18\x02 \x01(\x05\x12\x12\n\nposition_y\x18\x03 \x01(\x05\x12\x15\n\rtranslation_x\x18\x04 \x01(\x05\x12\x15\n\rtranslation_y\x18\x05 \x01(\x05\x12+\n\x04type\x18\x06 \x01(\x0e\x32\x1d.multiscope.events.Mouse.Type\"G\n\x04Type\x12\r\n\tUNDEFINED\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\x12\t\n\x05\x45NTER\x10\x03\x12\t\n\x05LEAVE\x10\x04\x12\x08\n\x04MOVE\x10\x05\x42#Z!multiscope/protos/events_go_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiscope.protos.events_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!multiscope/protos/events_go_proto'
  _globals['_WIDGET']._serialized_start=53
  _globals['_WIDGET']._serialized_end=160
  _globals['_WIDGET_TYPE']._serialized_start=128
  _globals['_WIDGET_TYPE']._serialized_end=160
  _globals['_KEYBOARD']._serialized_start=163
  _globals['_KEYBOARD']._serialized_end=331
  _globals['_KEYBOARD_TYPE']._serialized_start=292
  _globals['_KEYBOARD_TYPE']._serialized_end=331
  _globals['_MOUSE']._serialized_start=334
  _globals['_MOUSE']._serialized_end=558
  _globals['_MOUSE_TYPE']._serialized_start=487
  _globals['_MOUSE_TYPE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
