# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiscope/protos/plot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmultiscope/protos/plot.proto\x12\x0fmultiscope.plot\"2\n\x0bScalarsPlot\x12#\n\x04plot\x18\x01 \x01(\x0b\x32\x15.multiscope.plot.Plot\"v\n\x04Plot\x12*\n\x08plotters\x18\x02 \x03(\x0b\x32\x18.multiscope.plot.Plotter\x12 \n\x01x\x18\x03 \x01(\x0b\x32\x15.multiscope.plot.Axis\x12 \n\x01y\x18\x04 \x01(\x0b\x32\x15.multiscope.plot.Axis\"\x93\x01\n\x07Plotter\x12\x0e\n\x06legend\x18\x01 \x01(\t\x12\x31\n\nlineDrawer\x18\n \x01(\x0b\x32\x1b.multiscope.plot.LineDrawerH\x00\x12;\n\x0fhistogramDrawer\x18\x0b \x01(\x0b\x32 .multiscope.plot.HistogramDrawerH\x00\x42\x08\n\x06\x64rawer\";\n\x04\x41xis\x12\x33\n\nproperties\x18\n \x01(\x0b\x32\x1f.multiscope.plot.AxisProperties\"C\n\x0e\x41xisProperties\x12\r\n\x05label\x18\x01 \x01(\t\x12\x10\n\x08minValue\x18\x02 \x01(\x01\x12\x10\n\x08maxValue\x18\x03 \x01(\x01\"^\n\nLineDrawer\x12\x31\n\x06points\x18\x02 \x03(\x0b\x32!.multiscope.plot.LineDrawer.Point\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"v\n\x0fHistogramDrawer\x12\x32\n\x04\x62ins\x18\x02 \x03(\x0b\x32$.multiscope.plot.HistogramDrawer.Bin\x1a/\n\x03\x42in\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\x0e\n\x06weight\x18\x03 \x01(\x01\x42!Z\x1fmultiscope/protos/plot_go_protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiscope.protos.plot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037multiscope/protos/plot_go_proto'
  _SCALARSPLOT._serialized_start=49
  _SCALARSPLOT._serialized_end=99
  _PLOT._serialized_start=101
  _PLOT._serialized_end=219
  _PLOTTER._serialized_start=222
  _PLOTTER._serialized_end=369
  _AXIS._serialized_start=371
  _AXIS._serialized_end=430
  _AXISPROPERTIES._serialized_start=432
  _AXISPROPERTIES._serialized_end=499
  _LINEDRAWER._serialized_start=501
  _LINEDRAWER._serialized_end=595
  _LINEDRAWER_POINT._serialized_start=566
  _LINEDRAWER_POINT._serialized_end=595
  _HISTOGRAMDRAWER._serialized_start=597
  _HISTOGRAMDRAWER._serialized_end=715
  _HISTOGRAMDRAWER_BIN._serialized_start=668
  _HISTOGRAMDRAWER_BIN._serialized_end=715
# @@protoc_insertion_point(module_scope)
