# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: root.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tree_pb2 as tree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroot.proto\x12\x0fmultiscope.root\x1a\ntree.proto\"3\n\x08RootInfo\x12\'\n\x06layout\x18\x01 \x01(\x0b\x32\x17.multiscope.root.Layout\"1\n\x06Layout\x12\'\n\tdisplayed\x18\x02 \x03(\x0b\x32\x14.multiscope.NodePath\";\n\x10SetLayoutRequest\x12\'\n\x06layout\x18\x01 \x01(\x0b\x32\x17.multiscope.root.Layout\"\x13\n\x11SetLayoutResponse2\\\n\x04Root\x12T\n\tSetLayout\x12!.multiscope.root.SetLayoutRequest\x1a\".multiscope.root.SetLayoutResponse\"\x00\x42!Z\x1fmultiscope/protos/root_go_protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'root_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037multiscope/protos/root_go_proto'
  _ROOTINFO._serialized_start=43
  _ROOTINFO._serialized_end=94
  _LAYOUT._serialized_start=96
  _LAYOUT._serialized_end=145
  _SETLAYOUTREQUEST._serialized_start=147
  _SETLAYOUTREQUEST._serialized_end=206
  _SETLAYOUTRESPONSE._serialized_start=208
  _SETLAYOUTRESPONSE._serialized_end=227
  _ROOT._serialized_start=229
  _ROOT._serialized_end=321
# @@protoc_insertion_point(module_scope)
