# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiscope/protos/tensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from multiscope.protos import tree_pb2 as multiscope_dot_protos_dot_tree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emultiscope/protos/tensor.proto\x12\x12multiscope.tensors\x1a\x1cmultiscope/protos/tree.proto\",\n\x06Writer\x12\"\n\x04path\x18\x01 \x01(\x0b\x32\x14.multiscope.NodePath\"V\n\x05Shape\x12*\n\x03\x64im\x18\x02 \x03(\x0b\x32\x1d.multiscope.tensors.Shape.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"t\n\x06Tensor\x12+\n\x05\x64type\x18\x01 \x01(\x0e\x32\x1c.multiscope.tensors.DataType\x12(\n\x05shape\x18\x02 \x01(\x0b\x32\x19.multiscope.tensors.Shape\x12\x13\n\x07\x63ontent\x18\x04 \x01(\x0c\x42\x02\x08\x01\"6\n\x10NewWriterRequest\x12\"\n\x04path\x18\x01 \x01(\x0b\x32\x14.multiscope.NodePath\"o\n\x11NewWriterResponse\x12*\n\x06writer\x18\x01 \x01(\x0b\x32\x1a.multiscope.tensors.Writer\x12.\n\x10\x64\x65\x66\x61ultPanelPath\x18\x02 \x01(\x0b\x32\x14.multiscope.NodePath\"f\n\x0cWriteRequest\x12*\n\x06writer\x18\x01 \x01(\x0b\x32\x1a.multiscope.tensors.Writer\x12*\n\x06tensor\x18\x02 \x01(\x0b\x32\x1a.multiscope.tensors.Tensor\"\x0f\n\rWriteResponse\"@\n\x12ResetWriterRequest\x12*\n\x06writer\x18\x01 \x01(\x0b\x32\x1a.multiscope.tensors.Writer\"\x15\n\x13ResetWriterResponse*8\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0e\n\nDT_FLOAT32\x10\x01\x12\x0c\n\x08\x44T_UINT8\x10\x04\x32\x97\x02\n\x07Tensors\x12Z\n\tNewWriter\x12$.multiscope.tensors.NewWriterRequest\x1a%.multiscope.tensors.NewWriterResponse\"\x00\x12`\n\x0bResetWriter\x12&.multiscope.tensors.ResetWriterRequest\x1a\'.multiscope.tensors.ResetWriterResponse\"\x00\x12N\n\x05Write\x12 .multiscope.tensors.WriteRequest\x1a!.multiscope.tensors.WriteResponse\"\x00\x42#Z!multiscope/protos/tensor_go_protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiscope.protos.tensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!multiscope/protos/tensor_go_proto'
  _TENSOR.fields_by_name['content']._options = None
  _TENSOR.fields_by_name['content']._serialized_options = b'\010\001'
  _DATATYPE._serialized_start=715
  _DATATYPE._serialized_end=771
  _WRITER._serialized_start=84
  _WRITER._serialized_end=128
  _SHAPE._serialized_start=130
  _SHAPE._serialized_end=216
  _SHAPE_DIM._serialized_start=183
  _SHAPE_DIM._serialized_end=216
  _TENSOR._serialized_start=218
  _TENSOR._serialized_end=334
  _NEWWRITERREQUEST._serialized_start=336
  _NEWWRITERREQUEST._serialized_end=390
  _NEWWRITERRESPONSE._serialized_start=392
  _NEWWRITERRESPONSE._serialized_end=503
  _WRITEREQUEST._serialized_start=505
  _WRITEREQUEST._serialized_end=607
  _WRITERESPONSE._serialized_start=609
  _WRITERESPONSE._serialized_end=624
  _RESETWRITERREQUEST._serialized_start=626
  _RESETWRITERREQUEST._serialized_end=690
  _RESETWRITERRESPONSE._serialized_start=692
  _RESETWRITERRESPONSE._serialized_end=713
  _TENSORS._serialized_start=774
  _TENSORS._serialized_end=1053
# @@protoc_insertion_point(module_scope)
