# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from multiscope.protos import text_pb2 as multiscope_dot_protos_dot_text__pb2


class TextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewWriter = channel.unary_unary(
                '/multiscope.text.Text/NewWriter',
                request_serializer=multiscope_dot_protos_dot_text__pb2.NewWriterRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_text__pb2.NewWriterResponse.FromString,
                )
        self.NewHTMLWriter = channel.unary_unary(
                '/multiscope.text.Text/NewHTMLWriter',
                request_serializer=multiscope_dot_protos_dot_text__pb2.NewHTMLWriterRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_text__pb2.NewHTMLWriterResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/multiscope.text.Text/Write',
                request_serializer=multiscope_dot_protos_dot_text__pb2.WriteRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_text__pb2.WriteResponse.FromString,
                )
        self.WriteHTML = channel.unary_unary(
                '/multiscope.text.Text/WriteHTML',
                request_serializer=multiscope_dot_protos_dot_text__pb2.WriteHTMLRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_text__pb2.WriteHTMLResponse.FromString,
                )
        self.WriteCSS = channel.unary_unary(
                '/multiscope.text.Text/WriteCSS',
                request_serializer=multiscope_dot_protos_dot_text__pb2.WriteCSSRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_text__pb2.WriteCSSResponse.FromString,
                )


class TextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewWriter(self, request, context):
        """Create a new raw writer node in Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewHTMLWriter(self, request, context):
        """Create a new HTML writer node in Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write raw text to Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteHTML(self, request, context):
        """Write HTML text to Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteCSS(self, request, context):
        """Write CSS text to Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewWriter': grpc.unary_unary_rpc_method_handler(
                    servicer.NewWriter,
                    request_deserializer=multiscope_dot_protos_dot_text__pb2.NewWriterRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_text__pb2.NewWriterResponse.SerializeToString,
            ),
            'NewHTMLWriter': grpc.unary_unary_rpc_method_handler(
                    servicer.NewHTMLWriter,
                    request_deserializer=multiscope_dot_protos_dot_text__pb2.NewHTMLWriterRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_text__pb2.NewHTMLWriterResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=multiscope_dot_protos_dot_text__pb2.WriteRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_text__pb2.WriteResponse.SerializeToString,
            ),
            'WriteHTML': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteHTML,
                    request_deserializer=multiscope_dot_protos_dot_text__pb2.WriteHTMLRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_text__pb2.WriteHTMLResponse.SerializeToString,
            ),
            'WriteCSS': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteCSS,
                    request_deserializer=multiscope_dot_protos_dot_text__pb2.WriteCSSRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_text__pb2.WriteCSSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiscope.text.Text', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Text(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewWriter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.text.Text/NewWriter',
            multiscope_dot_protos_dot_text__pb2.NewWriterRequest.SerializeToString,
            multiscope_dot_protos_dot_text__pb2.NewWriterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewHTMLWriter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.text.Text/NewHTMLWriter',
            multiscope_dot_protos_dot_text__pb2.NewHTMLWriterRequest.SerializeToString,
            multiscope_dot_protos_dot_text__pb2.NewHTMLWriterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.text.Text/Write',
            multiscope_dot_protos_dot_text__pb2.WriteRequest.SerializeToString,
            multiscope_dot_protos_dot_text__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteHTML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.text.Text/WriteHTML',
            multiscope_dot_protos_dot_text__pb2.WriteHTMLRequest.SerializeToString,
            multiscope_dot_protos_dot_text__pb2.WriteHTMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteCSS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.text.Text/WriteCSS',
            multiscope_dot_protos_dot_text__pb2.WriteCSSRequest.SerializeToString,
            multiscope_dot_protos_dot_text__pb2.WriteCSSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
