# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multiscope/protos/ticker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from multiscope.protos import tree_pb2 as multiscope_dot_protos_dot_tree__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emultiscope/protos/ticker.proto\x12\x11multiscope.ticker\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cmultiscope/protos/tree.proto\",\n\x06Ticker\x12\"\n\x04path\x18\x01 \x01(\x0b\x32\x14.multiscope.NodePath\"6\n\x10NewTickerRequest\x12\"\n\x04path\x18\x01 \x01(\x0b\x32\x14.multiscope.NodePath\">\n\x11NewTickerResponse\x12)\n\x06ticker\x18\x01 \x01(\x0b\x32\x19.multiscope.ticker.Ticker\"\x8e\x02\n\nTickerData\x12\x0c\n\x04tick\x18\x02 \x01(\x03\x12\x36\n\x07periods\x18\x03 \x01(\x0b\x32%.multiscope.ticker.TickerData.Periods\x1a\xb9\x01\n\x07Periods\x12(\n\x05total\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12-\n\nexperiment\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12,\n\tcallbacks\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\'\n\x04idle\x18\x04 \x01(\x0b\x32\x19.google.protobuf.Duration\"\xe7\x01\n\x0cTickerAction\x12>\n\tsetPeriod\x18\x01 \x01(\x0b\x32).multiscope.ticker.TickerAction.SetPeriodH\x00\x12:\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\'.multiscope.ticker.TickerAction.CommandH\x00\x1a\x1e\n\tSetPeriod\x12\x11\n\tperiod_ms\x18\x01 \x01(\x03\"1\n\x07\x43ommand\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04STEP\x10\x01\x12\t\n\x05PAUSE\x10\x02\x12\x07\n\x03RUN\x10\x03\x42\x08\n\x06\x61\x63tion\"f\n\x0cWriteRequest\x12)\n\x06ticker\x18\x01 \x01(\x0b\x32\x19.multiscope.ticker.Ticker\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.multiscope.ticker.TickerData\"\x0f\n\rWriteResponse2\xab\x01\n\x07Tickers\x12R\n\x03New\x12#.multiscope.ticker.NewTickerRequest\x1a$.multiscope.ticker.NewTickerResponse\"\x00\x12L\n\x05Write\x12\x1f.multiscope.ticker.WriteRequest\x1a .multiscope.ticker.WriteResponse\"\x00\x42#Z!multiscope/protos/ticker_go_protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multiscope.protos.ticker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z!multiscope/protos/ticker_go_proto'
  _TICKER._serialized_start=115
  _TICKER._serialized_end=159
  _NEWTICKERREQUEST._serialized_start=161
  _NEWTICKERREQUEST._serialized_end=215
  _NEWTICKERRESPONSE._serialized_start=217
  _NEWTICKERRESPONSE._serialized_end=279
  _TICKERDATA._serialized_start=282
  _TICKERDATA._serialized_end=552
  _TICKERDATA_PERIODS._serialized_start=367
  _TICKERDATA_PERIODS._serialized_end=552
  _TICKERACTION._serialized_start=555
  _TICKERACTION._serialized_end=786
  _TICKERACTION_SETPERIOD._serialized_start=695
  _TICKERACTION_SETPERIOD._serialized_end=725
  _TICKERACTION_COMMAND._serialized_start=727
  _TICKERACTION_COMMAND._serialized_end=776
  _WRITEREQUEST._serialized_start=788
  _WRITEREQUEST._serialized_end=890
  _WRITERESPONSE._serialized_start=892
  _WRITERESPONSE._serialized_end=907
  _TICKERS._serialized_start=910
  _TICKERS._serialized_end=1081
# @@protoc_insertion_point(module_scope)
