# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from multiscope.protos import ticker_pb2 as multiscope_dot_protos_dot_ticker__pb2


class TickersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.New = channel.unary_unary(
                '/multiscope.ticker.Tickers/New',
                request_serializer=multiscope_dot_protos_dot_ticker__pb2.NewTickerRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_ticker__pb2.NewTickerResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/multiscope.ticker.Tickers/Write',
                request_serializer=multiscope_dot_protos_dot_ticker__pb2.WriteRequest.SerializeToString,
                response_deserializer=multiscope_dot_protos_dot_ticker__pb2.WriteResponse.FromString,
                )


class TickersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def New(self, request, context):
        """Create a new ticker node in Multiscope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write ticker data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'New': grpc.unary_unary_rpc_method_handler(
                    servicer.New,
                    request_deserializer=multiscope_dot_protos_dot_ticker__pb2.NewTickerRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_ticker__pb2.NewTickerResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=multiscope_dot_protos_dot_ticker__pb2.WriteRequest.FromString,
                    response_serializer=multiscope_dot_protos_dot_ticker__pb2.WriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multiscope.ticker.Tickers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tickers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def New(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.ticker.Tickers/New',
            multiscope_dot_protos_dot_ticker__pb2.NewTickerRequest.SerializeToString,
            multiscope_dot_protos_dot_ticker__pb2.NewTickerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multiscope.ticker.Tickers/Write',
            multiscope_dot_protos_dot_ticker__pb2.WriteRequest.SerializeToString,
            multiscope_dot_protos_dot_ticker__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
