// Copyright 2023 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Protocol buffer to stream text data.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: text.proto

package text_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	tree_go_proto "multiscope/protos/tree_go_proto"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Writer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TreeId *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// Path in the Multiscope tree.
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Writer) Reset() {
	*x = Writer{}
	mi := &file_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Writer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Writer) ProtoMessage() {}

func (x *Writer) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Writer.ProtoReflect.Descriptor instead.
func (*Writer) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{0}
}

func (x *Writer) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *Writer) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

type HTMLWriter struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TreeId *tree_go_proto.TreeID  `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	// Path in the Multiscope tree.
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTMLWriter) Reset() {
	*x = HTMLWriter{}
	mi := &file_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTMLWriter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTMLWriter) ProtoMessage() {}

func (x *HTMLWriter) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTMLWriter.ProtoReflect.Descriptor instead.
func (*HTMLWriter) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{1}
}

func (x *HTMLWriter) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *HTMLWriter) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Request to create a new (raw) text writer in the tree.
type NewWriterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID   `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWriterRequest) Reset() {
	*x = NewWriterRequest{}
	mi := &file_text_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWriterRequest) ProtoMessage() {}

func (x *NewWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWriterRequest.ProtoReflect.Descriptor instead.
func (*NewWriterRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{2}
}

func (x *NewWriterRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *NewWriterRequest) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Response after creating a new (raw) text writer in the tree.
type NewWriterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *Writer                `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewWriterResponse) Reset() {
	*x = NewWriterResponse{}
	mi := &file_text_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewWriterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWriterResponse) ProtoMessage() {}

func (x *NewWriterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWriterResponse.ProtoReflect.Descriptor instead.
func (*NewWriterResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{3}
}

func (x *NewWriterResponse) GetWriter() *Writer {
	if x != nil {
		return x.Writer
	}
	return nil
}

// Request to create a new HTML writer in the tree.
type NewHTMLWriterRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TreeId        *tree_go_proto.TreeID   `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Path          *tree_go_proto.NodePath `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewHTMLWriterRequest) Reset() {
	*x = NewHTMLWriterRequest{}
	mi := &file_text_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHTMLWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHTMLWriterRequest) ProtoMessage() {}

func (x *NewHTMLWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHTMLWriterRequest.ProtoReflect.Descriptor instead.
func (*NewHTMLWriterRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{4}
}

func (x *NewHTMLWriterRequest) GetTreeId() *tree_go_proto.TreeID {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *NewHTMLWriterRequest) GetPath() *tree_go_proto.NodePath {
	if x != nil {
		return x.Path
	}
	return nil
}

// Response after creating a new HTML writer in the tree.
type NewHTMLWriterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *HTMLWriter            `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewHTMLWriterResponse) Reset() {
	*x = NewHTMLWriterResponse{}
	mi := &file_text_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHTMLWriterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHTMLWriterResponse) ProtoMessage() {}

func (x *NewHTMLWriterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHTMLWriterResponse.ProtoReflect.Descriptor instead.
func (*NewHTMLWriterResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{5}
}

func (x *NewHTMLWriterResponse) GetWriter() *HTMLWriter {
	if x != nil {
		return x.Writer
	}
	return nil
}

// Request to write text to a Writer.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *Writer                `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_text_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{6}
}

func (x *WriteRequest) GetWriter() *Writer {
	if x != nil {
		return x.Writer
	}
	return nil
}

func (x *WriteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_text_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{7}
}

// Request to write HTML to a HTML writer.
type WriteHTMLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *HTMLWriter            `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteHTMLRequest) Reset() {
	*x = WriteHTMLRequest{}
	mi := &file_text_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteHTMLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteHTMLRequest) ProtoMessage() {}

func (x *WriteHTMLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteHTMLRequest.ProtoReflect.Descriptor instead.
func (*WriteHTMLRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{8}
}

func (x *WriteHTMLRequest) GetWriter() *HTMLWriter {
	if x != nil {
		return x.Writer
	}
	return nil
}

func (x *WriteHTMLRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type WriteHTMLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteHTMLResponse) Reset() {
	*x = WriteHTMLResponse{}
	mi := &file_text_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteHTMLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteHTMLResponse) ProtoMessage() {}

func (x *WriteHTMLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteHTMLResponse.ProtoReflect.Descriptor instead.
func (*WriteHTMLResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{9}
}

// Request to write CSS to a HTML writer.
type WriteCSSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writer        *HTMLWriter            `protobuf:"bytes,1,opt,name=writer,proto3" json:"writer,omitempty"`
	Css           string                 `protobuf:"bytes,2,opt,name=css,proto3" json:"css,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCSSRequest) Reset() {
	*x = WriteCSSRequest{}
	mi := &file_text_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCSSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCSSRequest) ProtoMessage() {}

func (x *WriteCSSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCSSRequest.ProtoReflect.Descriptor instead.
func (*WriteCSSRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{10}
}

func (x *WriteCSSRequest) GetWriter() *HTMLWriter {
	if x != nil {
		return x.Writer
	}
	return nil
}

func (x *WriteCSSRequest) GetCss() string {
	if x != nil {
		return x.Css
	}
	return ""
}

type WriteCSSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCSSResponse) Reset() {
	*x = WriteCSSResponse{}
	mi := &file_text_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCSSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCSSResponse) ProtoMessage() {}

func (x *WriteCSSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCSSResponse.ProtoReflect.Descriptor instead.
func (*WriteCSSResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{11}
}

var File_text_proto protoreflect.FileDescriptor

const file_text_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"text.proto\x12\x0fmultiscope.text\x1a\n" +
	"tree.proto\"_\n" +
	"\x06Writer\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"c\n" +
	"\n" +
	"HTMLWriter\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"i\n" +
	"\x10NewWriterRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"D\n" +
	"\x11NewWriterResponse\x12/\n" +
	"\x06writer\x18\x01 \x01(\v2\x17.multiscope.text.WriterR\x06writer\"m\n" +
	"\x14NewHTMLWriterRequest\x12+\n" +
	"\atree_id\x18\x01 \x01(\v2\x12.multiscope.TreeIDR\x06treeId\x12(\n" +
	"\x04path\x18\x02 \x01(\v2\x14.multiscope.NodePathR\x04path\"L\n" +
	"\x15NewHTMLWriterResponse\x123\n" +
	"\x06writer\x18\x01 \x01(\v2\x1b.multiscope.text.HTMLWriterR\x06writer\"S\n" +
	"\fWriteRequest\x12/\n" +
	"\x06writer\x18\x01 \x01(\v2\x17.multiscope.text.WriterR\x06writer\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x0f\n" +
	"\rWriteResponse\"[\n" +
	"\x10WriteHTMLRequest\x123\n" +
	"\x06writer\x18\x01 \x01(\v2\x1b.multiscope.text.HTMLWriterR\x06writer\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\"\x13\n" +
	"\x11WriteHTMLResponse\"X\n" +
	"\x0fWriteCSSRequest\x123\n" +
	"\x06writer\x18\x01 \x01(\v2\x1b.multiscope.text.HTMLWriterR\x06writer\x12\x10\n" +
	"\x03css\x18\x02 \x01(\tR\x03css\"\x12\n" +
	"\x10WriteCSSResponse2\xb1\x03\n" +
	"\x04Text\x12T\n" +
	"\tNewWriter\x12!.multiscope.text.NewWriterRequest\x1a\".multiscope.text.NewWriterResponse\"\x00\x12`\n" +
	"\rNewHTMLWriter\x12%.multiscope.text.NewHTMLWriterRequest\x1a&.multiscope.text.NewHTMLWriterResponse\"\x00\x12H\n" +
	"\x05Write\x12\x1d.multiscope.text.WriteRequest\x1a\x1e.multiscope.text.WriteResponse\"\x00\x12T\n" +
	"\tWriteHTML\x12!.multiscope.text.WriteHTMLRequest\x1a\".multiscope.text.WriteHTMLResponse\"\x00\x12Q\n" +
	"\bWriteCSS\x12 .multiscope.text.WriteCSSRequest\x1a!.multiscope.text.WriteCSSResponse\"\x00B!Z\x1fmultiscope/protos/text_go_protob\x06proto3"

var (
	file_text_proto_rawDescOnce sync.Once
	file_text_proto_rawDescData []byte
)

func file_text_proto_rawDescGZIP() []byte {
	file_text_proto_rawDescOnce.Do(func() {
		file_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)))
	})
	return file_text_proto_rawDescData
}

var file_text_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_text_proto_goTypes = []any{
	(*Writer)(nil),                 // 0: multiscope.text.Writer
	(*HTMLWriter)(nil),             // 1: multiscope.text.HTMLWriter
	(*NewWriterRequest)(nil),       // 2: multiscope.text.NewWriterRequest
	(*NewWriterResponse)(nil),      // 3: multiscope.text.NewWriterResponse
	(*NewHTMLWriterRequest)(nil),   // 4: multiscope.text.NewHTMLWriterRequest
	(*NewHTMLWriterResponse)(nil),  // 5: multiscope.text.NewHTMLWriterResponse
	(*WriteRequest)(nil),           // 6: multiscope.text.WriteRequest
	(*WriteResponse)(nil),          // 7: multiscope.text.WriteResponse
	(*WriteHTMLRequest)(nil),       // 8: multiscope.text.WriteHTMLRequest
	(*WriteHTMLResponse)(nil),      // 9: multiscope.text.WriteHTMLResponse
	(*WriteCSSRequest)(nil),        // 10: multiscope.text.WriteCSSRequest
	(*WriteCSSResponse)(nil),       // 11: multiscope.text.WriteCSSResponse
	(*tree_go_proto.TreeID)(nil),   // 12: multiscope.TreeID
	(*tree_go_proto.NodePath)(nil), // 13: multiscope.NodePath
}
var file_text_proto_depIdxs = []int32{
	12, // 0: multiscope.text.Writer.tree_id:type_name -> multiscope.TreeID
	13, // 1: multiscope.text.Writer.path:type_name -> multiscope.NodePath
	12, // 2: multiscope.text.HTMLWriter.tree_id:type_name -> multiscope.TreeID
	13, // 3: multiscope.text.HTMLWriter.path:type_name -> multiscope.NodePath
	12, // 4: multiscope.text.NewWriterRequest.tree_id:type_name -> multiscope.TreeID
	13, // 5: multiscope.text.NewWriterRequest.path:type_name -> multiscope.NodePath
	0,  // 6: multiscope.text.NewWriterResponse.writer:type_name -> multiscope.text.Writer
	12, // 7: multiscope.text.NewHTMLWriterRequest.tree_id:type_name -> multiscope.TreeID
	13, // 8: multiscope.text.NewHTMLWriterRequest.path:type_name -> multiscope.NodePath
	1,  // 9: multiscope.text.NewHTMLWriterResponse.writer:type_name -> multiscope.text.HTMLWriter
	0,  // 10: multiscope.text.WriteRequest.writer:type_name -> multiscope.text.Writer
	1,  // 11: multiscope.text.WriteHTMLRequest.writer:type_name -> multiscope.text.HTMLWriter
	1,  // 12: multiscope.text.WriteCSSRequest.writer:type_name -> multiscope.text.HTMLWriter
	2,  // 13: multiscope.text.Text.NewWriter:input_type -> multiscope.text.NewWriterRequest
	4,  // 14: multiscope.text.Text.NewHTMLWriter:input_type -> multiscope.text.NewHTMLWriterRequest
	6,  // 15: multiscope.text.Text.Write:input_type -> multiscope.text.WriteRequest
	8,  // 16: multiscope.text.Text.WriteHTML:input_type -> multiscope.text.WriteHTMLRequest
	10, // 17: multiscope.text.Text.WriteCSS:input_type -> multiscope.text.WriteCSSRequest
	3,  // 18: multiscope.text.Text.NewWriter:output_type -> multiscope.text.NewWriterResponse
	5,  // 19: multiscope.text.Text.NewHTMLWriter:output_type -> multiscope.text.NewHTMLWriterResponse
	7,  // 20: multiscope.text.Text.Write:output_type -> multiscope.text.WriteResponse
	9,  // 21: multiscope.text.Text.WriteHTML:output_type -> multiscope.text.WriteHTMLResponse
	11, // 22: multiscope.text.Text.WriteCSS:output_type -> multiscope.text.WriteCSSResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_text_proto_init() }
func file_text_proto_init() {
	if File_text_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_text_proto_goTypes,
		DependencyIndexes: file_text_proto_depIdxs,
		MessageInfos:      file_text_proto_msgTypes,
	}.Build()
	File_text_proto = out.File
	file_text_proto_goTypes = nil
	file_text_proto_depIdxs = nil
}
